Make c() fail more usefully when multiple dirs match

diff --git a/sh_common/functions/c b/sh_common/functions/c
--- a/sh_common/functions/c
+++ b/sh_common/functions/c
@@ -1,3 +1,7 @@
 c() {
-  cd ~/Code/*/$1;
+  if [[ "$(stat ~/Code/*/$1 | wc -l)" -gt 1 ]]; then
+    echo 'FATAL: multiple directories match, cannot select' >&2
+    return 1
+  fi
+  cd ~/Code/*/$1
 }
